### ISSUE TITLE
confused by the paper

### ISSUE THREAD

**Issue by smarengin** [liuxingbin/dbot#6]
Hi, Authors,
Thank you for good work!
I am confused about the paper: 
1. you say the teacher  is not important, but the best results is done by using data-richer teacher, exceed others by large margin.
2. you say the best practice is multi-stage by distill itself, but the best results is done by 1 stage with longer epochs and good teacher.
So I am confused. Is there some point I don't understand?

**Comment by liuxingbin** [comment]
Thanks for your interest.
Generally, sec.6 is an investigation part.
1. Teacher is not important when the data and architecture are the same, i.e., only pre-trained methods of teacher are different. (Tab.1).  We assume the same conclusion if teachers are all pre-trained on 400M ITp, which we can't verify since data used in CLIP is not publicly available.
2. Indeed, the best practice is multi-stage only when the data are the same during the multi-stage process. The reason for the best results achieved in 1 stage in our paper is that data-richer information will be lost in the second stage. Therefore, we should keep the data-richer teacher and perform longer epochs. However, we expect better results if we distill student with 400M ITp in all stages.

**Comment by smarengin** [comment]
Thank for your reply!
Does the teacher DALL-E in tab. 1 is CLIP model？and in this case, even the teacher is good enough, multi-stage distill for MAE architecture is not better than other teacher, is that right?

**Comment by liuxingbin** [comment]
For a fair comparison, we pre-train DALL-E with IN1K.

**Comment by smarengin** [comment]
OK, thank you
